# Generated by Django 5.2.7 on 2025-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unit',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
